name: NetherHub
main: me.zoxu.netherhub.Main
version: 1.1.0
api-version: 1.15
author: Zoxu

depend:
   - CoreAPI

commands:
   NetherHub:
      description: NetherHub main command
      usage: /<command> [loc]
      aliases: [nh]